# --------------------------------------------
# SERVER CONFIGURATION
# -------------------------------------------- 
server: 
  port: 8080
  
# --------------------------------------------
# ROUTING ACTUATOR CONFIGURATION 
# --------------------------------------------    
management:
  endpoints:
    gateway:
      enabled: true
    web:
      base-path: /manage

# --------------------------------------------
# LOG CONFIGURATION
# --------------------------------------------  
logging:
  level:
    org:
      springframework: DEBUG
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    
# --------------------------------------------
# SPRING APP CONFIGURATION
# --------------------------------------------    
spring:
  jmx:
    enabled: false
  aop: 
    proxy-target-class: true        
  profiles: 
    active: loc   
            
# --------------------------------------------
# MQ CONFIGURATION
# --------------------------------------------             
  rabbitmq:
    host: ${RABBIT_URI:127.0.0.1}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}
    
# --------------------------------------------
# SLEUTH CONFIGURATION
# --------------------------------------------    
  sleuth:
    enabled: true
    sampler:
      percentage: 0.0
    rxjava:
      schedulers:
        hook:
          enabled: false

# --------------------------------------------
# CUSTOM CONFIGURATIONS 
# --------------------------------------------
custom: 
  logger:
    enabled: false   
  common:
    swagger: false