# --------------------------------------------
# SERVER CONFIGURATION
# -------------------------------------------- 
server: 
  port: 8080
  
# --------------------------------------------
# SPRING SECURITY CONFIGURATION 
# --------------------------------------------    
management:
  server:
    servlet:
      context-path: /admin
    
# --------------------------------------------
# LOG CONFIGURATION
# --------------------------------------------    
logging:
   file: ${spring.application.name}.log
   path: /var/log   
   pattern: 
     console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"  
    
# --------------------------------------------
# SPRING APP CONFIGURATION
# --------------------------------------------    
spring:    
  jmx:
    default-domain: cloud.config.server
  aop: 
    proxy-target-class: true        
  profiles: 
    active: dev  

# --------------------------------------------
# MQ CONFIGURATION
# --------------------------------------------             
  rabbitmq:
    host: ${RABBIT_URI:172.21.1.251}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}
    
# --------------------------------------------
# SLEUTH CONFIGURATION
# --------------------------------------------    
  sleuth:
    enabled: true
    sampler:
      percentage: 0.0
    rxjava:
      schedulers:
        hook:
          enabled: false

# --------------------------------------------
# CUSTOM CONFIGURATIONS 
# --------------------------------------------
custom: 
  logger:
    enabled: false   
  common:
    swagger: false