# --------------------------------------------
# SERVER CONFIGURATION
# -------------------------------------------- 
server: 
  port: 8080
  
# --------------------------------------------
# SPRING SECURITY CONFIGURATION 
# --------------------------------------------    
management:
  context-path: /admin
    
# --------------------------------------------
# LOG CONFIGURATION
# --------------------------------------------    
logging:
   file: ${spring.application.name}.log
   path: /var/log   
    
# --------------------------------------------
# SPRING APP CONFIGURATION
# --------------------------------------------    
spring:    
  jmx:
    default-domain: cloud.config.server
  aop: 
    proxy-target-class: false        
  profiles: 
    active: def   
        
# --------------------------------------------
# MQ CONFIGURATION
# --------------------------------------------             
  rabbitmq:
    host: ${RABBIT_URI:127.0.0.1}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}
    
# --------------------------------------------
# SLEUTH CONFIGURATION
# --------------------------------------------    
  sleuth:
    enabled: false
    sampler:
      percentage: 0.0
    rxjava:
      schedulers:
        hook:
          enabled: false 
              
# --------------------------------------------
# CUSTOM CONFIGURATIONS 
# --------------------------------------------
vac: 
  logger:
    enabled: false   
  common:
    swagger: false